const MATCHES = [
  {id:1,  date:"Jun 11",time:"3 PM",  group:"A",home:"México",       away:"Sudáfrica",       venue:"Ciudad de México"},
  {id:2,  date:"Jun 11",time:"10 PM", group:"A",home:"Corea del Sur",away:"Rep. Checa",       venue:"Zapopan"},
  {id:3,  date:"Jun 12",time:"3 PM",  group:"B",home:"Canadá",       away:"Bosnia-Herz.",     venue:"Toronto"},
  {id:4,  date:"Jun 12",time:"9 PM",  group:"D",home:"EE.UU.",       away:"Paraguay",         venue:"Inglewood"},
  {id:5,  date:"Jun 13",time:"3 PM",  group:"B",home:"Qatar",        away:"Suiza",            venue:"Santa Clara"},
  {id:6,  date:"Jun 13",time:"6 PM",  group:"C",home:"Brasil",       away:"Marruecos",        venue:"E. Rutherford"},
  {id:7,  date:"Jun 13",time:"9 PM",  group:"C",home:"Haití",        away:"Escocia",          venue:"Foxborough"},
  {id:8,  date:"Jun 14",time:"3 PM",  group:"E",home:"Alemania",     away:"Curazao",          venue:"Toronto"},
  {id:9,  date:"Jun 14",time:"6 PM",  group:"F",home:"Países Bajos", away:"Túnez",            venue:"Guadalajara"},
  {id:10, date:"Jun 14",time:"9 PM",  group:"E",home:"C. de Marfil", away:"Ecuador",          venue:"Kansas City"},
  {id:11, date:"Jun 15",time:"1 PM",  group:"H",home:"España",       away:"Cabo Verde",       venue:"Atlanta"},
  {id:12, date:"Jun 15",time:"6 PM",  group:"G",home:"Bélgica",      away:"Egipto",           venue:"Seattle"},
  {id:13, date:"Jun 15",time:"6 PM",  group:"H",home:"Arabia Saudí", away:"Uruguay",          venue:"Miami"},
  {id:14, date:"Jun 16",time:"12 AM", group:"G",home:"Irán",         away:"Nueva Zelanda",    venue:"Inglewood"},
  {id:15, date:"Jun 16",time:"3 PM",  group:"I",home:"Francia",      away:"Senegal",          venue:"E. Rutherford"},
  {id:16, date:"Jun 16",time:"6 PM",  group:"I",home:"Irak",         away:"Noruega",          venue:"Foxborough"},
  {id:17, date:"Jun 16",time:"9 PM",  group:"J",home:"Argentina",    away:"Argelia",          venue:"Kansas City"},
  {id:18, date:"Jun 17",time:"12 AM", group:"J",home:"Austria",      away:"Jordania",         venue:"Santa Clara"},
  {id:19, date:"Jun 17",time:"1 PM",  group:"K",home:"Portugal",     away:"DR Congo",         venue:"Houston"},
  {id:20, date:"Jun 17",time:"4 PM",  group:"L",home:"Inglaterra",   away:"Croacia",          venue:"Arlington"},
  {id:21, date:"Jun 17",time:"7 PM",  group:"L",home:"Ghana",        away:"Panamá",           venue:"Toronto"},
  {id:22, date:"Jun 17",time:"10 PM", group:"K",home:"Uzbekistán",   away:"Colombia",         venue:"Ciudad de México"},
  {id:23, date:"Jun 18",time:"12 PM", group:"A",home:"Rep. Checa",   away:"Sudáfrica",        venue:"Atlanta"},
  {id:24, date:"Jun 18",time:"3 PM",  group:"B",home:"Suiza",        away:"Bosnia-Herz.",     venue:"Inglewood"},
  {id:25, date:"Jun 18",time:"6 PM",  group:"B",home:"Canadá",       away:"Qatar",            venue:"Vancouver"},
  {id:26, date:"Jun 18",time:"11 PM", group:"A",home:"México",       away:"Corea del Sur",    venue:"Zapopan"},
  {id:27, date:"Jun 19",time:"3 PM",  group:"D",home:"EE.UU.",       away:"Australia",        venue:"Seattle"},
  {id:28, date:"Jun 19",time:"6 PM",  group:"C",home:"Escocia",      away:"Marruecos",        venue:"Foxborough"},
  {id:29, date:"Jun 19",time:"9 PM",  group:"C",home:"Brasil",       away:"Haití",            venue:"Filadelfia"},
  {id:30, date:"Jun 20",time:"12 AM", group:"D",home:"Turquía",      away:"Paraguay",         venue:"Santa Clara"},
  {id:31, date:"Jun 20",time:"1 PM",  group:"F",home:"Países Bajos", away:"Suecia",           venue:"Houston"},
  {id:32, date:"Jun 20",time:"4 PM",  group:"E",home:"Alemania",     away:"C. de Marfil",     venue:"Toronto"},
  {id:33, date:"Jun 20",time:"8 PM",  group:"E",home:"Ecuador",      away:"Curazao",          venue:"Kansas City"},
  {id:34, date:"Jun 20",time:"10 PM", group:"F",home:"Túnez",        away:"Japón",            venue:"Guadalajara"},
  {id:35, date:"Jun 21",time:"3 PM",  group:"G",home:"Bélgica",      away:"Nueva Zelanda",    venue:"Seattle"},
  {id:36, date:"Jun 21",time:"6 PM",  group:"H",home:"España",       away:"Arabia Saudí",     venue:"Miami"},
  {id:37, date:"Jun 21",time:"9 PM",  group:"G",home:"Irán",         away:"Egipto",           venue:"Inglewood"},
  {id:38, date:"Jun 21",time:"9 PM",  group:"H",home:"Cabo Verde",   away:"Uruguay",          venue:"Atlanta"},
  {id:39, date:"Jun 22",time:"3 PM",  group:"I",home:"Francia",      away:"Irak",             venue:"E. Rutherford"},
  {id:40, date:"Jun 22",time:"6 PM",  group:"J",home:"Argentina",    away:"Austria",          venue:"Kansas City"},
  {id:41, date:"Jun 22",time:"9 PM",  group:"I",home:"Senegal",      away:"Noruega",          venue:"Foxborough"},
  {id:42, date:"Jun 23",time:"12 AM", group:"J",home:"Argelia",      away:"Jordania",         venue:"Santa Clara"},
  {id:43, date:"Jun 23",time:"1 PM",  group:"L",home:"Inglaterra",   away:"Ghana",            venue:"Arlington"},
  {id:44, date:"Jun 23",time:"4 PM",  group:"K",home:"Portugal",     away:"Uzbekistán",       venue:"Houston"},
  {id:45, date:"Jun 23",time:"7 PM",  group:"K",home:"DR Congo",     away:"Colombia",         venue:"Ciudad de México"},
  {id:46, date:"Jun 23",time:"10 PM", group:"L",home:"Croacia",      away:"Panamá",           venue:"Toronto"},
  {id:47, date:"Jun 24",time:"3 PM",  group:"A",home:"México",       away:"Rep. Checa",       venue:"Ciudad de México"},
  {id:48, date:"Jun 24",time:"3 PM",  group:"A",home:"Corea del Sur",away:"Sudáfrica",        venue:"Monterrey"},
  {id:49, date:"Jun 24",time:"9 PM",  group:"B",home:"Suiza",        away:"Qatar",            venue:"Kansas City"},
  {id:50, date:"Jun 24",time:"9 PM",  group:"B",home:"Bosnia-Herz.", away:"Canadá",           venue:"Inglewood"},
  {id:51, date:"Jun 25",time:"3 PM",  group:"C",home:"Brasil",       away:"Escocia",          venue:"E. Rutherford"},
  {id:52, date:"Jun 25",time:"3 PM",  group:"C",home:"Marruecos",    away:"Haití",            venue:"Foxborough"},
  {id:53, date:"Jun 25",time:"9 PM",  group:"D",home:"Paraguay",     away:"Australia",        venue:"Santa Clara"},
  {id:54, date:"Jun 25",time:"9 PM",  group:"D",home:"Turquía",      away:"EE.UU.",           venue:"Seattle"},
  {id:55, date:"Jun 26",time:"3 PM",  group:"E",home:"C. de Marfil", away:"Curazao",          venue:"Toronto"},
  {id:56, date:"Jun 26",time:"3 PM",  group:"E",home:"Ecuador",      away:"Alemania",         venue:"Kansas City"},
  {id:57, date:"Jun 26",time:"9 PM",  group:"F",home:"Países Bajos", away:"Japón",            venue:"Houston"},
  {id:58, date:"Jun 26",time:"9 PM",  group:"F",home:"Suecia",       away:"Túnez",            venue:"Guadalajara"},
  {id:59, date:"Jun 27",time:"3 PM",  group:"G",home:"Nueva Zelanda",away:"Egipto",           venue:"Inglewood"},
  {id:60, date:"Jun 27",time:"3 PM",  group:"G",home:"Irán",         away:"Bélgica",          venue:"Seattle"},
  {id:61, date:"Jun 27",time:"9 PM",  group:"H",home:"Arabia Saudí", away:"Cabo Verde",       venue:"Miami"},
  {id:62, date:"Jun 27",time:"9 PM",  group:"H",home:"Uruguay",      away:"España",           venue:"Atlanta"},
  {id:63, date:"Jun 28",time:"3 PM",  group:"I",home:"Irak",         away:"Francia",          venue:"Foxborough"},
  {id:64, date:"Jun 28",time:"3 PM",  group:"I",home:"Noruega",      away:"Senegal",          venue:"E. Rutherford"},
  {id:65, date:"Jun 28",time:"9 PM",  group:"J",home:"Jordania",     away:"Argentina",        venue:"Santa Clara"},
  {id:66, date:"Jun 28",time:"9 PM",  group:"J",home:"Austria",      away:"Argelia",          venue:"Kansas City"},
  {id:67, date:"Jun 29",time:"3 PM",  group:"K",home:"Colombia",     away:"Portugal",         venue:"Houston"},
  {id:68, date:"Jun 29",time:"3 PM",  group:"K",home:"Uzbekistán",   away:"DR Congo",         venue:"Ciudad de México"},
  {id:69, date:"Jun 29",time:"9 PM",  group:"L",home:"Croacia",      away:"Ghana",            venue:"Toronto"},
  {id:70, date:"Jun 29",time:"9 PM",  group:"L",home:"Panamá",       away:"Inglaterra",       venue:"Arlington"},
];

const GROUPS = {
  A:["México","Corea del Sur","Sudáfrica","Rep. Checa"],
  B:["Canadá","Bosnia-Herz.","Qatar","Suiza"],
  C:["Brasil","Marruecos","Haití","Escocia"],
  D:["EE.UU.","Paraguay","Australia","Turquía"],
  E:["Alemania","C. de Marfil","Ecuador","Curazao"],
  F:["Países Bajos","Suecia","Túnez","Japón"],
  G:["Bélgica","Egipto","Irán","Nueva Zelanda"],
  H:["España","Cabo Verde","Arabia Saudí","Uruguay"],
  I:["Francia","Senegal","Irak","Noruega"],
  J:["Argentina","Argelia","Austria","Jordania"],
  K:["Portugal","DR Congo","Uzbekistán","Colombia"],
  L:["Inglaterra","Croacia","Ghana","Panamá"],
};

const SCORING = {
  exact_score: 3,        // resultado exacto
  correct_winner: 1,     // solo acertó ganador o empate
  group_both_order: 10,  // 1° y 2° en orden correcto
  group_both_swap: 6,    // 1° y 2° correctos pero invertidos
  group_one: 3,          // acertó solo uno de los clasificados
  runner_up: 20,         // acertó subcampeón final
  champion: 40,          // acertó campeón final
  elim_correct: 5,       // acertó clasificante en eliminatorias
  elim_exact: 3,         // bonus resultado exacto en eliminatorias
  phase2_change: -2,     // penalización por cambio en fase 2
};
